name: Kim Kenefsky
favicon: null
layout_spectrum: 0.32313
typography_spectrum: 0.64417
title: The Kenefsky Group Real Estate Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaecfb'
    - '#a3755b'
    - '#67412c'
    - '#26242f'
    - '#f8b59a'
  brandStrength: 1
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 1
purpose: []
