name: Kim Kenefsky
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64417
title: The Kenefsky Group Real Estate Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#98a8b9'
    - '#403732'
    - '#191718'
    - '#818181'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
