name: Kim Kenefsky
favicon: null
layout_spectrum: 0.96873
typography_spectrum: 0.64417
title: The Kenefsky Group Real Estate Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b5b5b5'
    - '#342b27'
    - '#827876'
    - '#81cfea'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
