name: Kim Kenefsky
favicon: null
layout_spectrum: 0.32313
typography_spectrum: 0.64417
title: The Kenefsky Group Real Estate Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a5e80'
    - '#273d52'
    - '#b3b7b8'
    - '#858d94'
    - '#f1e5cf'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
