name: Kim Kenefsky
favicon: null
layout_spectrum: 0.6493492529261857
typography_spectrum: 0.5964279954787344
title: The Kenefsky Group Real Estate Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090502'
    - '#ffffff'
    - '#3d3936'
    - '#8a7769'
    - '#b4a497'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
