name: Kim Kenefsky
favicon: null
layout_spectrum: 0.42219
typography_spectrum: 0.64417
title: The Kenefsky Group Real Estate Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdc7b7'
    - '#f2e6c0'
    - '#a39882'
    - '#786a4f'
    - '#feffef'
  brandStrength: 1
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
