name: Kim Kenefsky
favicon: null
layout_spectrum: 0.75884
typography_spectrum: 0.64417
title: The Kenefsky Group Real Estate Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c3ab89'
    - '#8e8272'
    - '#230f00'
    - '#4e391f'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
