name: Kim Kenefsky
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74417
title: The Kenefsky Group Real Estate Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dac0a7'
    - '#87796c'
    - '#020202'
    - '#4d3a2b'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
